package com.simplypeople.entity;
// Generated 6 May, 2019 2:14:19 PM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 * Employee generated by hbm2java
 */
@Entity
@NamedQueries({
	@NamedQuery(name = "Employee.findAll", query = "SELECT u FROM Employee u ORDER BY u.fullname"),
	@NamedQuery(name = "Employee.findByEmail", query = "SELECT u FROM Employee u WHERE u.email = :email"),
	@NamedQuery(name = "Employee.countAll", query = "SELECT Count(*) FROM Employee u"),
	@NamedQuery(name = "Employee.checkLogin", query = "SELECT u FROM Employee u WHERE u.email = :email AND password = :password")
})
@Table(name = "employee", catalog = "simplypeople")
public class Employee implements java.io.Serializable {

	private Integer employeeId;
	private String email;
	private String password;
	private String fullname;

	public Employee() {
	}

	public Employee(Integer employeeId, String email, String fullname, String password) {
		this(email, fullname, password);
		this.employeeId = employeeId;
	}
	
	public Employee(String email,String fullname, String password) {
		super();
		this.email = email;
		this.password = password;
		this.fullname = fullname;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "employee_id", unique = true, nullable = false)
	public Integer getEmployeeId() {
		return this.employeeId;
	}

	public void setEmployeeId(Integer employeeId) {
		this.employeeId = employeeId;
	}

	@Column(name = "email", nullable = false, length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 15)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "fullname", nullable = false, length = 30)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

}
