package com.simplypeople.entity;
// Generated 9 May, 2019 6:08:05 PM by Hibernate Tools 5.2.10.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

import com.simplypeople.entity.Employee;
import com.simplypeople.entity.Users;

/**
 * Grievances generated by hbm2java
 */
@Entity
@Table(name = "Grievances", catalog = "simplypeople")
@NamedQueries({
	@NamedQuery(name = "Grievances.listAll", query = "SELECT g FROM Grievances g "),
	@NamedQuery(name = "Grievances.countAll", query = "SELECT COUNT(g) FROM Grievances g"),
	@NamedQuery(name = "Grievances.findByAdminAndEmployee", 
		query = "SELECT g FROM Grievances g WHERE g.users.usersId =:usersId"
				+ " AND g.employee.employeeId =:employeeId"),
})
public class Grievances implements java.io.Serializable {

	private Integer grievancesId;
	private Employee employee;
	private Users users;
	private String comment;

	public Grievances() {
	}

	public Grievances(Employee employee, Users users, String comment) {
		
		this.employee = employee;
		this.users = users;
		this.comment = comment;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "grievances_id", unique = true, nullable = false)
	public Integer getGrievancesId() {
		return this.grievancesId;
	}

	public void setGrievancesId(Integer grievancesId) {
		this.grievancesId = grievancesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employee_id", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "users_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "comment", nullable = false, length = 45)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
