package com.simplypeople.entity;
// Generated 9 May, 2019 2:59:00 PM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.simplypeople.entity.Employee;
import com.simplypeople.entity.Projectmanager;

/**
 * Review generated by hbm2java
 */
@Entity
@Table(name = "Review", catalog = "simplypeople")
@NamedQueries({
	@NamedQuery(name = "Review.listAll", query = "SELECT r FROM Review r "),
	@NamedQuery(name = "Review.countAll", query = "SELECT COUNT(r) FROM Review r"),
	@NamedQuery(name = "Review.findByProjectmanagerAndEmployee", 
		query = "SELECT r FROM Review r WHERE r.projectmanager.pmid =:pmid"
				+ " AND r.employee.employeeId =:employeeId"),
})
public class Review implements java.io.Serializable {

	private Integer reviewId;
	private Employee employee;
	private Projectmanager projectmanager;
	private String comment;
	private float rating;

	public Review() {
	}

	public Review(Employee employee, Projectmanager projectmanager, String comment, float rating) {
		this.employee = employee;
		this.projectmanager = projectmanager;
		this.comment = comment;
		this.rating = rating;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "review_id", unique = true, nullable = false)
	public Integer getReviewId() {
		return this.reviewId;
	}

	public void setReviewId(Integer reviewId) {
		this.reviewId = reviewId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employee_id", nullable = false)
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pmid", nullable = false)
	public Projectmanager getProjectmanager() {
		return this.projectmanager;
	}

	public void setProjectmanager(Projectmanager projectmanager) {
		this.projectmanager = projectmanager;
	}

	@Column(name = "comment", nullable = false, length = 45)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "rating", nullable = false, precision = 12, scale = 0)
	public float getRating() {
		return this.rating;
	}

	public void setRating(float rating) {
		this.rating = rating;
	}

}
